name: Mirror Repository

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  mirror:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v3

      # Step 2: Add the target repository as a remote
      - name: Add target remote
        run: |
          git remote add target https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/Fiverrsupport/ACC001.git
      # Step 3: Push changes to the target repository
      - name: Push to target repository
        run: |
          git push target --mirror
